export const data = {
  tracks: [
    {
      id: "j6pE0OCJ1dzzF4jDAfZqo",
      name: "Text Track",
      type: "text",
      clipIds: [
        "KYHX2z-ri4MMlvaFxWhvu",
        "x-za4-9wxfFQS6-oclEv3",
        "UAt0d19eDNoTumgG39JEi",
        "ItIHPIVg4TgTdufCIy8rM",
        "W-wEigsEBrS0sh1bg0h1I",
        "ZZz4MyhuwzL_J71j8P8fb",
      ],
    },
    {
      id: "4ZJpOEYr11nVzVYnlFQJ-",
      name: "Video Track",
      type: "video",
      clipIds: ["WOOmjrV0ezj4nMqEH3hkX", "3H-8GCFW3BqU1v2AJiuRt", "MnkX0eHpFwueGnqhkh9fy"],
    },
  ],
  clips: {
    "KYHX2z-ri4MMlvaFxWhvu": {
      type: "Text",
      id: "KYHX2z-ri4MMlvaFxWhvu",
      name: "Text",
      src: "",
      timing: {
        display: {
          from: 0,
          to: 2000000,
        },
        trim: {
          from: 0,
          to: 0,
        },
        duration: 2000000,
        playbackRate: 1,
      },
      transform: {
        x: 540,
        y: 960,
        width: 960,
        height: 67.2,
        angle: 0,
        opacity: 1,
        zIndex: 20,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {
        fontSize: 56,
        fontFamily: "Outfit",
        color: "#ffffff",
        align: "center",
        shadow: {
          color: "#000000",
          alpha: 0.5,
          blur: 12,
          offsetX: 0,
          offsetY: 2,
        },
      },
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      text: "Carden Jung",
      effects: [],
    },
    WOOmjrV0ezj4nMqEH3hkX: {
      type: "Video",
      id: "WOOmjrV0ezj4nMqEH3hkX",
      name: "Carden Jung (3).mp4",
      src: "https://cdn.scenify.io/mockuser/1a9f75e7-3741-4b03-9fa2-e582571e49de-Carden_Jung__3_.mp4",
      timing: {
        display: {
          from: 2000000,
          to: 7119000,
        },
        trim: {
          from: 1280000,
          to: 6399000,
        },
        duration: 5119000,
        playbackRate: 1,
      },
      transform: {
        x: -180,
        y: 0,
        width: 1440,
        height: 1920,
        angle: 0,
        opacity: 1,
        zIndex: 10,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {},
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      audio: true,
      volume: 1,
      effects: [],
    },
    "x-za4-9wxfFQS6-oclEv3": {
      type: "Text",
      id: "x-za4-9wxfFQS6-oclEv3",
      name: "Text",
      src: "",
      timing: {
        display: {
          from: 2000000,
          to: 7119000,
        },
        trim: {
          from: 0,
          to: 0,
        },
        duration: 5119000,
        playbackRate: 1,
      },
      transform: {
        x: 90,
        y: 1760,
        width: 900,
        height: 45.6,
        angle: 0,
        opacity: 1,
        zIndex: 20,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {
        fontSize: 38,
        fontFamily: "Inter",
        color: "#ffffff",
        align: "left",
        shadow: {
          color: "#000000",
          alpha: 0.75,
          blur: 8,
          offsetX: 0,
          offsetY: 2,
        },
      },
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      text: "Carden Jung",
      effects: [],
    },
    UAt0d19eDNoTumgG39JEi: {
      type: "Text",
      id: "UAt0d19eDNoTumgG39JEi",
      name: "Text",
      src: "",
      timing: {
        display: {
          from: 7119000,
          to: 9119000,
        },
        trim: {
          from: 0,
          to: 0,
        },
        duration: 2000000,
        playbackRate: 1,
      },
      transform: {
        x: 540,
        y: 960,
        width: 960,
        height: 67.2,
        angle: 0,
        opacity: 1,
        zIndex: 20,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {
        fontSize: 56,
        fontFamily: "Outfit",
        color: "#ffffff",
        align: "center",
        shadow: {
          color: "#000000",
          alpha: 0.5,
          blur: 12,
          offsetX: 0,
          offsetY: 2,
        },
      },
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      text: "Blessteva Johnson",
      effects: [],
    },
    "3H-8GCFW3BqU1v2AJiuRt": {
      type: "Video",
      id: "3H-8GCFW3BqU1v2AJiuRt",
      name: "Blessteva Johnson.mp4",
      src: "https://cdn.scenify.io/bj60.mp4",
      timing: {
        display: {
          from: 9119000,
          to: 19519000,
        },
        trim: {
          from: 560000,
          to: 10960000,
        },
        duration: 10400000,
        playbackRate: 1,
      },
      transform: {
        x: -420,
        y: 0,
        width: 1920,
        height: 1920,
        angle: 0,
        opacity: 1,
        zIndex: 10,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {},
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      audio: true,
      volume: 1,
      effects: [],
    },
    ItIHPIVg4TgTdufCIy8rM: {
      type: "Text",
      id: "ItIHPIVg4TgTdufCIy8rM",
      name: "Text",
      src: "",
      timing: {
        display: {
          from: 9119000,
          to: 19519000,
        },
        trim: {
          from: 0,
          to: 0,
        },
        duration: 10400000,
        playbackRate: 1,
      },
      transform: {
        x: 90,
        y: 1760,
        width: 900,
        height: 45.6,
        angle: 0,
        opacity: 1,
        zIndex: 20,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {
        fontSize: 38,
        fontFamily: "Inter",
        color: "#ffffff",
        align: "left",
        shadow: {
          color: "#000000",
          alpha: 0.75,
          blur: 8,
          offsetX: 0,
          offsetY: 2,
        },
      },
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      text: "Blessteva Johnson",
      effects: [],
    },
    "W-wEigsEBrS0sh1bg0h1I": {
      type: "Text",
      id: "W-wEigsEBrS0sh1bg0h1I",
      name: "Text",
      src: "",
      timing: {
        display: {
          from: 19519000,
          to: 21519000,
        },
        trim: {
          from: 0,
          to: 0,
        },
        duration: 2000000,
        playbackRate: 1,
      },
      transform: {
        x: 540,
        y: 960,
        width: 960,
        height: 67.2,
        angle: 0,
        opacity: 1,
        zIndex: 20,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {
        fontSize: 56,
        fontFamily: "Outfit",
        color: "#ffffff",
        align: "center",
        shadow: {
          color: "#000000",
          alpha: 0.5,
          blur: 12,
          offsetX: 0,
          offsetY: 2,
        },
      },
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      text: "Elizabeth Santandreu",
      effects: [],
    },
    MnkX0eHpFwueGnqhkh9fy: {
      type: "Video",
      id: "MnkX0eHpFwueGnqhkh9fy",
      name: "Elizabeth Santandreu (5).mp4",
      src: "https://cdn.scenify.io/mockuser/e367d639-3325-4095-b1ac-9aa049a0c7ab-Elizabeth_Santandreu__5_.mp4",
      timing: {
        display: {
          from: 21519000,
          to: 27039000,
        },
        trim: {
          from: 80000,
          to: 5600000,
        },
        duration: 5520000,
        playbackRate: 1,
      },
      transform: {
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        angle: 0,
        opacity: 1,
        zIndex: 10,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {},
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      audio: true,
      volume: 1,
      effects: [],
    },
    ZZz4MyhuwzL_J71j8P8fb: {
      type: "Text",
      id: "ZZz4MyhuwzL_J71j8P8fb",
      name: "Text",
      src: "",
      timing: {
        display: {
          from: 21519000,
          to: 27039000,
        },
        trim: {
          from: 0,
          to: 0,
        },
        duration: 5520000,
        playbackRate: 1,
      },
      transform: {
        x: 90,
        y: 1760,
        width: 900,
        height: 45.6,
        angle: 0,
        opacity: 1,
        zIndex: 20,
        flip: {
          x: false,
          y: false,
        },
      },
      style: {
        fontSize: 38,
        fontFamily: "Inter",
        color: "#ffffff",
        align: "left",
        shadow: {
          color: "#000000",
          alpha: 0.75,
          blur: 8,
          offsetX: 0,
          offsetY: 2,
        },
      },
      chromaKey: {
        enabled: false,
        color: "#00FF00",
        similarity: 0.1,
        spill: 0,
      },
      colorAdjustment: {
        enabled: false,
        type: "basic",
        basic: {},
        hsl: {},
        curves: {},
      },
      locked: false,
      metadata: {},
      text: "Elizabeth Santandreu",
      effects: [],
    },
  },
  settings: {
    width: 1080,
    height: 1920,
    fps: 30,
    backgroundColor: "#111111",
  },
};
