
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const EditorCanvasPanel: typeof import("../app/components/editor/CanvasPanel.vue").default
export const Editor: typeof import("../app/components/editor/Editor.vue").default
export const EditorHeader: typeof import("../app/components/editor/Header.vue").default
export const EditorConstants: typeof import("../app/components/editor/constants").default
export const EditorMediaPanelAudioItem: typeof import("../app/components/editor/media-panel/AudioItem.vue").default
export const EditorMediaPanel: typeof import("../app/components/editor/media-panel/MediaPanel.vue").default
export const EditorMediaPanelCaptions: typeof import("../app/components/editor/media-panel/PanelCaptions.vue").default
export const EditorMediaPanelEffects: typeof import("../app/components/editor/media-panel/PanelEffects.vue").default
export const EditorMediaPanelElements: typeof import("../app/components/editor/media-panel/PanelElements.vue").default
export const EditorMediaPanelImages: typeof import("../app/components/editor/media-panel/PanelImages.vue").default
export const EditorMediaPanelMusic: typeof import("../app/components/editor/media-panel/PanelMusic.vue").default
export const EditorMediaPanelSFX: typeof import("../app/components/editor/media-panel/PanelSFX.vue").default
export const EditorMediaPanelText: typeof import("../app/components/editor/media-panel/PanelText.vue").default
export const EditorMediaPanelTransitions: typeof import("../app/components/editor/media-panel/PanelTransitions.vue").default
export const EditorMediaPanelUploads: typeof import("../app/components/editor/media-panel/PanelUploads.vue").default
export const EditorMediaPanelVideos: typeof import("../app/components/editor/media-panel/PanelVideos.vue").default
export const EditorMediaPanelVoiceovers: typeof import("../app/components/editor/media-panel/PanelVoiceovers.vue").default
export const EditorMediaPanelTabBar: typeof import("../app/components/editor/media-panel/TabBar.vue").default
export const EditorPropertiesPanel: typeof import("../app/components/editor/properties-panel/PropertiesPanel.vue").default
export const EditorTimeline: typeof import("../app/components/editor/timeline/Timeline.vue").default
export const EditorTimelinePlayhead: typeof import("../app/components/editor/timeline/TimelinePlayhead.vue").default
export const EditorTimelineRuler: typeof import("../app/components/editor/timeline/TimelineRuler.vue").default
export const EditorTimelineStudioSync: typeof import("../app/components/editor/timeline/TimelineStudioSync.vue").default
export const EditorTimelineToolbar: typeof import("../app/components/editor/timeline/TimelineToolbar.vue").default
export const EditorTimelineConstants: typeof import("../app/components/editor/timeline/timeline-constants").default
export const EditorTimelineTimelineCanvas: typeof import("../app/components/editor/timeline/timeline/canvas").default
export const EditorTimelineTimelineClipsAudio: typeof import("../app/components/editor/timeline/timeline/clips/audio").default
export const EditorTimelineTimelineClipsBase: typeof import("../app/components/editor/timeline/timeline/clips/base").default
export const EditorTimelineTimelineClipsCaption: typeof import("../app/components/editor/timeline/timeline/clips/caption").default
export const EditorTimelineTimelineClipsEffect: typeof import("../app/components/editor/timeline/timeline/clips/effect").default
export const EditorTimelineTimelineClipsImage: typeof import("../app/components/editor/timeline/timeline/clips/image").default
export const EditorTimelineTimelineClips: typeof import("../app/components/editor/timeline/timeline/clips/index").default
export const EditorTimelineTimelineClipsText: typeof import("../app/components/editor/timeline/timeline/clips/text").default
export const EditorTimelineTimelineClipsTransition: typeof import("../app/components/editor/timeline/timeline/clips/transition").default
export const EditorTimelineTimelineClipsVideo: typeof import("../app/components/editor/timeline/timeline/clips/video").default
export const EditorTimelineTimelineControlsConstants: typeof import("../app/components/editor/timeline/timeline/controls/constants").default
export const EditorTimelineTimelineControls: typeof import("../app/components/editor/timeline/timeline/controls/index").default
export const EditorTimelineTimelineControlsRender: typeof import("../app/components/editor/timeline/timeline/controls/render").default
export const EditorTimelineTimelineControlsResizeAction: typeof import("../app/components/editor/timeline/timeline/controls/resize-action").default
export const EditorTimelineTimelineControlsTrimAction: typeof import("../app/components/editor/timeline/timeline/controls/trim-action").default
export const EditorTimelineTimelineControlsUtils: typeof import("../app/components/editor/timeline/timeline/controls/utils").default
export const EditorTimelineTimelineData: typeof import("../app/components/editor/timeline/timeline/data").default
export const EditorTimelineTimelineEventEmitter: typeof import("../app/components/editor/timeline/timeline/event-emitter").default
export const EditorTimelineTimelineGuidelinesUtils: typeof import("../app/components/editor/timeline/timeline/guidelines/utils").default
export const EditorTimelineTimelineHandlersDragHandler: typeof import("../app/components/editor/timeline/timeline/handlers/drag-handler").default
export const EditorTimelineTimelineHandlersModifyHandler: typeof import("../app/components/editor/timeline/timeline/handlers/modify-handler").default
export const EditorTimelineTimelineHandlersSelection: typeof import("../app/components/editor/timeline/timeline/handlers/selection").default
export const EditorTimelineTimeline: typeof import("../app/components/editor/timeline/timeline/index").default
export const EditorTimelineTimelineObjectsTransitionButton: typeof import("../app/components/editor/timeline/timeline/objects/transition-button").default
export const EditorTimelineTimelineScrollbar: typeof import("../app/components/editor/timeline/timeline/scrollbar/index").default
export const EditorTimelineTimelineScrollbarTypes: typeof import("../app/components/editor/timeline/timeline/scrollbar/types").default
export const EditorTimelineTimelineScrollbarUtil: typeof import("../app/components/editor/timeline/timeline/scrollbar/util").default
export const EditorTimelineTimelineTrack: typeof import("../app/components/editor/timeline/timeline/track").default
export const EditorTimelineTimelineUtilsFilmstrip: typeof import("../app/components/editor/timeline/timeline/utils/filmstrip").default
export const EditorTimelineTimelineUtilsThumbnailCache: typeof import("../app/components/editor/timeline/timeline/utils/thumbnail-cache").default
export const SharedIcons: typeof import("../app/components/shared/icons").default
export const SharedLogos: typeof import("../app/components/shared/logos").default
export const NuxtWelcome: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const Button: typeof import("../app/components/ui/button/index").Button
export const DropdownMenu: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenu
export const DropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuCheckboxItem
export const DropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuContent
export const DropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuGroup
export const DropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuItem
export const DropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuLabel
export const DropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuRadioGroup
export const DropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuRadioItem
export const DropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSeparator
export const DropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuShortcut
export const DropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSub
export const DropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSubContent
export const DropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSubTrigger
export const DropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuTrigger
export const DropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuPortal
export const Input: typeof import("../app/components/ui/input/index").Input
export const Popover: typeof import("../app/components/ui/popover/index").Popover
export const PopoverAnchor: typeof import("../app/components/ui/popover/index").PopoverAnchor
export const PopoverContent: typeof import("../app/components/ui/popover/index").PopoverContent
export const PopoverTrigger: typeof import("../app/components/ui/popover/index").PopoverTrigger
export const InputGroup: typeof import("../app/components/ui/input-group/index").InputGroup
export const InputGroupAddon: typeof import("../app/components/ui/input-group/index").InputGroupAddon
export const InputGroupButton: typeof import("../app/components/ui/input-group/index").InputGroupButton
export const InputGroupInput: typeof import("../app/components/ui/input-group/index").InputGroupInput
export const InputGroupText: typeof import("../app/components/ui/input-group/index").InputGroupText
export const InputGroupTextarea: typeof import("../app/components/ui/input-group/index").InputGroupTextarea
export const ResizableHandle: typeof import("../app/components/ui/resizable/index").ResizableHandle
export const ResizablePanel: typeof import("../app/components/ui/resizable/index").ResizablePanel
export const ResizablePanelGroup: typeof import("../app/components/ui/resizable/index").ResizablePanelGroup
export const ScrollArea: typeof import("../app/components/ui/scroll-area/index").ScrollArea
export const ScrollBar: typeof import("../app/components/ui/scroll-area/index").ScrollBar
export const Separator: typeof import("../app/components/ui/separator/index").Separator
export const Slider: typeof import("../app/components/ui/slider/index").Slider
export const Tabs: typeof import("../app/components/ui/tabs/index").Tabs
export const TabsContent: typeof import("../app/components/ui/tabs/index").TabsContent
export const TabsList: typeof import("../app/components/ui/tabs/index").TabsList
export const TabsTrigger: typeof import("../app/components/ui/tabs/index").TabsTrigger
export const Tooltip: typeof import("../app/components/ui/tooltip/index").Tooltip
export const TooltipContent: typeof import("../app/components/ui/tooltip/index").TooltipContent
export const TooltipProvider: typeof import("../app/components/ui/tooltip/index").TooltipProvider
export const TooltipTrigger: typeof import("../app/components/ui/tooltip/index").TooltipTrigger
export const Textarea: typeof import("../app/components/ui/textarea/index").Textarea
export const NuxtPage: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/pages/runtime/page-placeholder").default
export const NoScript: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyEditorCanvasPanel: LazyComponent<typeof import("../app/components/editor/CanvasPanel.vue").default>
export const LazyEditor: LazyComponent<typeof import("../app/components/editor/Editor.vue").default>
export const LazyEditorHeader: LazyComponent<typeof import("../app/components/editor/Header.vue").default>
export const LazyEditorConstants: LazyComponent<typeof import("../app/components/editor/constants").default>
export const LazyEditorMediaPanelAudioItem: LazyComponent<typeof import("../app/components/editor/media-panel/AudioItem.vue").default>
export const LazyEditorMediaPanel: LazyComponent<typeof import("../app/components/editor/media-panel/MediaPanel.vue").default>
export const LazyEditorMediaPanelCaptions: LazyComponent<typeof import("../app/components/editor/media-panel/PanelCaptions.vue").default>
export const LazyEditorMediaPanelEffects: LazyComponent<typeof import("../app/components/editor/media-panel/PanelEffects.vue").default>
export const LazyEditorMediaPanelElements: LazyComponent<typeof import("../app/components/editor/media-panel/PanelElements.vue").default>
export const LazyEditorMediaPanelImages: LazyComponent<typeof import("../app/components/editor/media-panel/PanelImages.vue").default>
export const LazyEditorMediaPanelMusic: LazyComponent<typeof import("../app/components/editor/media-panel/PanelMusic.vue").default>
export const LazyEditorMediaPanelSFX: LazyComponent<typeof import("../app/components/editor/media-panel/PanelSFX.vue").default>
export const LazyEditorMediaPanelText: LazyComponent<typeof import("../app/components/editor/media-panel/PanelText.vue").default>
export const LazyEditorMediaPanelTransitions: LazyComponent<typeof import("../app/components/editor/media-panel/PanelTransitions.vue").default>
export const LazyEditorMediaPanelUploads: LazyComponent<typeof import("../app/components/editor/media-panel/PanelUploads.vue").default>
export const LazyEditorMediaPanelVideos: LazyComponent<typeof import("../app/components/editor/media-panel/PanelVideos.vue").default>
export const LazyEditorMediaPanelVoiceovers: LazyComponent<typeof import("../app/components/editor/media-panel/PanelVoiceovers.vue").default>
export const LazyEditorMediaPanelTabBar: LazyComponent<typeof import("../app/components/editor/media-panel/TabBar.vue").default>
export const LazyEditorPropertiesPanel: LazyComponent<typeof import("../app/components/editor/properties-panel/PropertiesPanel.vue").default>
export const LazyEditorTimeline: LazyComponent<typeof import("../app/components/editor/timeline/Timeline.vue").default>
export const LazyEditorTimelinePlayhead: LazyComponent<typeof import("../app/components/editor/timeline/TimelinePlayhead.vue").default>
export const LazyEditorTimelineRuler: LazyComponent<typeof import("../app/components/editor/timeline/TimelineRuler.vue").default>
export const LazyEditorTimelineStudioSync: LazyComponent<typeof import("../app/components/editor/timeline/TimelineStudioSync.vue").default>
export const LazyEditorTimelineToolbar: LazyComponent<typeof import("../app/components/editor/timeline/TimelineToolbar.vue").default>
export const LazyEditorTimelineConstants: LazyComponent<typeof import("../app/components/editor/timeline/timeline-constants").default>
export const LazyEditorTimelineTimelineCanvas: LazyComponent<typeof import("../app/components/editor/timeline/timeline/canvas").default>
export const LazyEditorTimelineTimelineClipsAudio: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/audio").default>
export const LazyEditorTimelineTimelineClipsBase: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/base").default>
export const LazyEditorTimelineTimelineClipsCaption: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/caption").default>
export const LazyEditorTimelineTimelineClipsEffect: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/effect").default>
export const LazyEditorTimelineTimelineClipsImage: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/image").default>
export const LazyEditorTimelineTimelineClips: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/index").default>
export const LazyEditorTimelineTimelineClipsText: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/text").default>
export const LazyEditorTimelineTimelineClipsTransition: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/transition").default>
export const LazyEditorTimelineTimelineClipsVideo: LazyComponent<typeof import("../app/components/editor/timeline/timeline/clips/video").default>
export const LazyEditorTimelineTimelineControlsConstants: LazyComponent<typeof import("../app/components/editor/timeline/timeline/controls/constants").default>
export const LazyEditorTimelineTimelineControls: LazyComponent<typeof import("../app/components/editor/timeline/timeline/controls/index").default>
export const LazyEditorTimelineTimelineControlsRender: LazyComponent<typeof import("../app/components/editor/timeline/timeline/controls/render").default>
export const LazyEditorTimelineTimelineControlsResizeAction: LazyComponent<typeof import("../app/components/editor/timeline/timeline/controls/resize-action").default>
export const LazyEditorTimelineTimelineControlsTrimAction: LazyComponent<typeof import("../app/components/editor/timeline/timeline/controls/trim-action").default>
export const LazyEditorTimelineTimelineControlsUtils: LazyComponent<typeof import("../app/components/editor/timeline/timeline/controls/utils").default>
export const LazyEditorTimelineTimelineData: LazyComponent<typeof import("../app/components/editor/timeline/timeline/data").default>
export const LazyEditorTimelineTimelineEventEmitter: LazyComponent<typeof import("../app/components/editor/timeline/timeline/event-emitter").default>
export const LazyEditorTimelineTimelineGuidelinesUtils: LazyComponent<typeof import("../app/components/editor/timeline/timeline/guidelines/utils").default>
export const LazyEditorTimelineTimelineHandlersDragHandler: LazyComponent<typeof import("../app/components/editor/timeline/timeline/handlers/drag-handler").default>
export const LazyEditorTimelineTimelineHandlersModifyHandler: LazyComponent<typeof import("../app/components/editor/timeline/timeline/handlers/modify-handler").default>
export const LazyEditorTimelineTimelineHandlersSelection: LazyComponent<typeof import("../app/components/editor/timeline/timeline/handlers/selection").default>
export const LazyEditorTimelineTimeline: LazyComponent<typeof import("../app/components/editor/timeline/timeline/index").default>
export const LazyEditorTimelineTimelineObjectsTransitionButton: LazyComponent<typeof import("../app/components/editor/timeline/timeline/objects/transition-button").default>
export const LazyEditorTimelineTimelineScrollbar: LazyComponent<typeof import("../app/components/editor/timeline/timeline/scrollbar/index").default>
export const LazyEditorTimelineTimelineScrollbarTypes: LazyComponent<typeof import("../app/components/editor/timeline/timeline/scrollbar/types").default>
export const LazyEditorTimelineTimelineScrollbarUtil: LazyComponent<typeof import("../app/components/editor/timeline/timeline/scrollbar/util").default>
export const LazyEditorTimelineTimelineTrack: LazyComponent<typeof import("../app/components/editor/timeline/timeline/track").default>
export const LazyEditorTimelineTimelineUtilsFilmstrip: LazyComponent<typeof import("../app/components/editor/timeline/timeline/utils/filmstrip").default>
export const LazyEditorTimelineTimelineUtilsThumbnailCache: LazyComponent<typeof import("../app/components/editor/timeline/timeline/utils/thumbnail-cache").default>
export const LazySharedIcons: LazyComponent<typeof import("../app/components/shared/icons").default>
export const LazySharedLogos: LazyComponent<typeof import("../app/components/shared/logos").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyButton: LazyComponent<typeof import("../app/components/ui/button/index").Button>
export const LazyDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenu>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuCheckboxItem>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuContent>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuGroup>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuItem>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuLabel>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuRadioGroup>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuRadioItem>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSeparator>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuShortcut>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSub>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSubContent>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuSubTrigger>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuTrigger>
export const LazyDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index").DropdownMenuPortal>
export const LazyInput: LazyComponent<typeof import("../app/components/ui/input/index").Input>
export const LazyPopover: LazyComponent<typeof import("../app/components/ui/popover/index").Popover>
export const LazyPopoverAnchor: LazyComponent<typeof import("../app/components/ui/popover/index").PopoverAnchor>
export const LazyPopoverContent: LazyComponent<typeof import("../app/components/ui/popover/index").PopoverContent>
export const LazyPopoverTrigger: LazyComponent<typeof import("../app/components/ui/popover/index").PopoverTrigger>
export const LazyInputGroup: LazyComponent<typeof import("../app/components/ui/input-group/index").InputGroup>
export const LazyInputGroupAddon: LazyComponent<typeof import("../app/components/ui/input-group/index").InputGroupAddon>
export const LazyInputGroupButton: LazyComponent<typeof import("../app/components/ui/input-group/index").InputGroupButton>
export const LazyInputGroupInput: LazyComponent<typeof import("../app/components/ui/input-group/index").InputGroupInput>
export const LazyInputGroupText: LazyComponent<typeof import("../app/components/ui/input-group/index").InputGroupText>
export const LazyInputGroupTextarea: LazyComponent<typeof import("../app/components/ui/input-group/index").InputGroupTextarea>
export const LazyResizableHandle: LazyComponent<typeof import("../app/components/ui/resizable/index").ResizableHandle>
export const LazyResizablePanel: LazyComponent<typeof import("../app/components/ui/resizable/index").ResizablePanel>
export const LazyResizablePanelGroup: LazyComponent<typeof import("../app/components/ui/resizable/index").ResizablePanelGroup>
export const LazyScrollArea: LazyComponent<typeof import("../app/components/ui/scroll-area/index").ScrollArea>
export const LazyScrollBar: LazyComponent<typeof import("../app/components/ui/scroll-area/index").ScrollBar>
export const LazySeparator: LazyComponent<typeof import("../app/components/ui/separator/index").Separator>
export const LazySlider: LazyComponent<typeof import("../app/components/ui/slider/index").Slider>
export const LazyTabs: LazyComponent<typeof import("../app/components/ui/tabs/index").Tabs>
export const LazyTabsContent: LazyComponent<typeof import("../app/components/ui/tabs/index").TabsContent>
export const LazyTabsList: LazyComponent<typeof import("../app/components/ui/tabs/index").TabsList>
export const LazyTabsTrigger: LazyComponent<typeof import("../app/components/ui/tabs/index").TabsTrigger>
export const LazyTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/index").Tooltip>
export const LazyTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/index").TooltipContent>
export const LazyTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/index").TooltipProvider>
export const LazyTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/index").TooltipTrigger>
export const LazyTextarea: LazyComponent<typeof import("../app/components/ui/textarea/index").Textarea>
export const LazyNuxtPage: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/pages/runtime/page-placeholder").default>
export const LazyNoScript: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
