
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'EditorCanvasPanel': typeof import("../../app/components/editor/CanvasPanel.vue").default
  'Editor': typeof import("../../app/components/editor/Editor.vue").default
  'EditorHeader': typeof import("../../app/components/editor/Header.vue").default
  'EditorConstants': typeof import("../../app/components/editor/constants").default
  'EditorMediaPanelAudioItem': typeof import("../../app/components/editor/media-panel/AudioItem.vue").default
  'EditorMediaPanel': typeof import("../../app/components/editor/media-panel/MediaPanel.vue").default
  'EditorMediaPanelCaptions': typeof import("../../app/components/editor/media-panel/PanelCaptions.vue").default
  'EditorMediaPanelEffects': typeof import("../../app/components/editor/media-panel/PanelEffects.vue").default
  'EditorMediaPanelElements': typeof import("../../app/components/editor/media-panel/PanelElements.vue").default
  'EditorMediaPanelImages': typeof import("../../app/components/editor/media-panel/PanelImages.vue").default
  'EditorMediaPanelMusic': typeof import("../../app/components/editor/media-panel/PanelMusic.vue").default
  'EditorMediaPanelSFX': typeof import("../../app/components/editor/media-panel/PanelSFX.vue").default
  'EditorMediaPanelText': typeof import("../../app/components/editor/media-panel/PanelText.vue").default
  'EditorMediaPanelTransitions': typeof import("../../app/components/editor/media-panel/PanelTransitions.vue").default
  'EditorMediaPanelUploads': typeof import("../../app/components/editor/media-panel/PanelUploads.vue").default
  'EditorMediaPanelVideos': typeof import("../../app/components/editor/media-panel/PanelVideos.vue").default
  'EditorMediaPanelVoiceovers': typeof import("../../app/components/editor/media-panel/PanelVoiceovers.vue").default
  'EditorMediaPanelTabBar': typeof import("../../app/components/editor/media-panel/TabBar.vue").default
  'EditorPropertiesPanel': typeof import("../../app/components/editor/properties-panel/PropertiesPanel.vue").default
  'EditorTimeline': typeof import("../../app/components/editor/timeline/Timeline.vue").default
  'EditorTimelinePlayhead': typeof import("../../app/components/editor/timeline/TimelinePlayhead.vue").default
  'EditorTimelineRuler': typeof import("../../app/components/editor/timeline/TimelineRuler.vue").default
  'EditorTimelineStudioSync': typeof import("../../app/components/editor/timeline/TimelineStudioSync.vue").default
  'EditorTimelineToolbar': typeof import("../../app/components/editor/timeline/TimelineToolbar.vue").default
  'EditorTimelineConstants': typeof import("../../app/components/editor/timeline/timeline-constants").default
  'EditorTimelineTimelineCanvas': typeof import("../../app/components/editor/timeline/timeline/canvas").default
  'EditorTimelineTimelineClipsAudio': typeof import("../../app/components/editor/timeline/timeline/clips/audio").default
  'EditorTimelineTimelineClipsBase': typeof import("../../app/components/editor/timeline/timeline/clips/base").default
  'EditorTimelineTimelineClipsCaption': typeof import("../../app/components/editor/timeline/timeline/clips/caption").default
  'EditorTimelineTimelineClipsEffect': typeof import("../../app/components/editor/timeline/timeline/clips/effect").default
  'EditorTimelineTimelineClipsImage': typeof import("../../app/components/editor/timeline/timeline/clips/image").default
  'EditorTimelineTimelineClips': typeof import("../../app/components/editor/timeline/timeline/clips/index").default
  'EditorTimelineTimelineClipsText': typeof import("../../app/components/editor/timeline/timeline/clips/text").default
  'EditorTimelineTimelineClipsTransition': typeof import("../../app/components/editor/timeline/timeline/clips/transition").default
  'EditorTimelineTimelineClipsVideo': typeof import("../../app/components/editor/timeline/timeline/clips/video").default
  'EditorTimelineTimelineControlsConstants': typeof import("../../app/components/editor/timeline/timeline/controls/constants").default
  'EditorTimelineTimelineControls': typeof import("../../app/components/editor/timeline/timeline/controls/index").default
  'EditorTimelineTimelineControlsRender': typeof import("../../app/components/editor/timeline/timeline/controls/render").default
  'EditorTimelineTimelineControlsResizeAction': typeof import("../../app/components/editor/timeline/timeline/controls/resize-action").default
  'EditorTimelineTimelineControlsTrimAction': typeof import("../../app/components/editor/timeline/timeline/controls/trim-action").default
  'EditorTimelineTimelineControlsUtils': typeof import("../../app/components/editor/timeline/timeline/controls/utils").default
  'EditorTimelineTimelineData': typeof import("../../app/components/editor/timeline/timeline/data").default
  'EditorTimelineTimelineEventEmitter': typeof import("../../app/components/editor/timeline/timeline/event-emitter").default
  'EditorTimelineTimelineGuidelinesUtils': typeof import("../../app/components/editor/timeline/timeline/guidelines/utils").default
  'EditorTimelineTimelineHandlersDragHandler': typeof import("../../app/components/editor/timeline/timeline/handlers/drag-handler").default
  'EditorTimelineTimelineHandlersModifyHandler': typeof import("../../app/components/editor/timeline/timeline/handlers/modify-handler").default
  'EditorTimelineTimelineHandlersSelection': typeof import("../../app/components/editor/timeline/timeline/handlers/selection").default
  'EditorTimelineTimeline': typeof import("../../app/components/editor/timeline/timeline/index").default
  'EditorTimelineTimelineObjectsTransitionButton': typeof import("../../app/components/editor/timeline/timeline/objects/transition-button").default
  'EditorTimelineTimelineScrollbar': typeof import("../../app/components/editor/timeline/timeline/scrollbar/index").default
  'EditorTimelineTimelineScrollbarTypes': typeof import("../../app/components/editor/timeline/timeline/scrollbar/types").default
  'EditorTimelineTimelineScrollbarUtil': typeof import("../../app/components/editor/timeline/timeline/scrollbar/util").default
  'EditorTimelineTimelineTrack': typeof import("../../app/components/editor/timeline/timeline/track").default
  'EditorTimelineTimelineUtilsFilmstrip': typeof import("../../app/components/editor/timeline/timeline/utils/filmstrip").default
  'EditorTimelineTimelineUtilsThumbnailCache': typeof import("../../app/components/editor/timeline/timeline/utils/thumbnail-cache").default
  'SharedIcons': typeof import("../../app/components/shared/icons").default
  'SharedLogos': typeof import("../../app/components/shared/logos").default
  'NuxtWelcome': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'Button': typeof import("../../app/components/ui/button/index").Button
  'DropdownMenu': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenu
  'DropdownMenuCheckboxItem': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuCheckboxItem
  'DropdownMenuContent': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuContent
  'DropdownMenuGroup': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuGroup
  'DropdownMenuItem': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuItem
  'DropdownMenuLabel': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuLabel
  'DropdownMenuRadioGroup': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuRadioGroup
  'DropdownMenuRadioItem': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuRadioItem
  'DropdownMenuSeparator': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSeparator
  'DropdownMenuShortcut': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuShortcut
  'DropdownMenuSub': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSub
  'DropdownMenuSubContent': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSubContent
  'DropdownMenuSubTrigger': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSubTrigger
  'DropdownMenuTrigger': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuTrigger
  'DropdownMenuPortal': typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuPortal
  'Input': typeof import("../../app/components/ui/input/index").Input
  'Popover': typeof import("../../app/components/ui/popover/index").Popover
  'PopoverAnchor': typeof import("../../app/components/ui/popover/index").PopoverAnchor
  'PopoverContent': typeof import("../../app/components/ui/popover/index").PopoverContent
  'PopoverTrigger': typeof import("../../app/components/ui/popover/index").PopoverTrigger
  'InputGroup': typeof import("../../app/components/ui/input-group/index").InputGroup
  'InputGroupAddon': typeof import("../../app/components/ui/input-group/index").InputGroupAddon
  'InputGroupButton': typeof import("../../app/components/ui/input-group/index").InputGroupButton
  'InputGroupInput': typeof import("../../app/components/ui/input-group/index").InputGroupInput
  'InputGroupText': typeof import("../../app/components/ui/input-group/index").InputGroupText
  'InputGroupTextarea': typeof import("../../app/components/ui/input-group/index").InputGroupTextarea
  'ResizableHandle': typeof import("../../app/components/ui/resizable/index").ResizableHandle
  'ResizablePanel': typeof import("../../app/components/ui/resizable/index").ResizablePanel
  'ResizablePanelGroup': typeof import("../../app/components/ui/resizable/index").ResizablePanelGroup
  'ScrollArea': typeof import("../../app/components/ui/scroll-area/index").ScrollArea
  'ScrollBar': typeof import("../../app/components/ui/scroll-area/index").ScrollBar
  'Separator': typeof import("../../app/components/ui/separator/index").Separator
  'Slider': typeof import("../../app/components/ui/slider/index").Slider
  'Tabs': typeof import("../../app/components/ui/tabs/index").Tabs
  'TabsContent': typeof import("../../app/components/ui/tabs/index").TabsContent
  'TabsList': typeof import("../../app/components/ui/tabs/index").TabsList
  'TabsTrigger': typeof import("../../app/components/ui/tabs/index").TabsTrigger
  'Tooltip': typeof import("../../app/components/ui/tooltip/index").Tooltip
  'TooltipContent': typeof import("../../app/components/ui/tooltip/index").TooltipContent
  'TooltipProvider': typeof import("../../app/components/ui/tooltip/index").TooltipProvider
  'TooltipTrigger': typeof import("../../app/components/ui/tooltip/index").TooltipTrigger
  'Textarea': typeof import("../../app/components/ui/textarea/index").Textarea
  'NuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/pages/runtime/page-placeholder").default
  'NoScript': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyEditorCanvasPanel': LazyComponent<typeof import("../../app/components/editor/CanvasPanel.vue").default>
  'LazyEditor': LazyComponent<typeof import("../../app/components/editor/Editor.vue").default>
  'LazyEditorHeader': LazyComponent<typeof import("../../app/components/editor/Header.vue").default>
  'LazyEditorConstants': LazyComponent<typeof import("../../app/components/editor/constants").default>
  'LazyEditorMediaPanelAudioItem': LazyComponent<typeof import("../../app/components/editor/media-panel/AudioItem.vue").default>
  'LazyEditorMediaPanel': LazyComponent<typeof import("../../app/components/editor/media-panel/MediaPanel.vue").default>
  'LazyEditorMediaPanelCaptions': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelCaptions.vue").default>
  'LazyEditorMediaPanelEffects': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelEffects.vue").default>
  'LazyEditorMediaPanelElements': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelElements.vue").default>
  'LazyEditorMediaPanelImages': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelImages.vue").default>
  'LazyEditorMediaPanelMusic': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelMusic.vue").default>
  'LazyEditorMediaPanelSFX': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelSFX.vue").default>
  'LazyEditorMediaPanelText': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelText.vue").default>
  'LazyEditorMediaPanelTransitions': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelTransitions.vue").default>
  'LazyEditorMediaPanelUploads': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelUploads.vue").default>
  'LazyEditorMediaPanelVideos': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelVideos.vue").default>
  'LazyEditorMediaPanelVoiceovers': LazyComponent<typeof import("../../app/components/editor/media-panel/PanelVoiceovers.vue").default>
  'LazyEditorMediaPanelTabBar': LazyComponent<typeof import("../../app/components/editor/media-panel/TabBar.vue").default>
  'LazyEditorPropertiesPanel': LazyComponent<typeof import("../../app/components/editor/properties-panel/PropertiesPanel.vue").default>
  'LazyEditorTimeline': LazyComponent<typeof import("../../app/components/editor/timeline/Timeline.vue").default>
  'LazyEditorTimelinePlayhead': LazyComponent<typeof import("../../app/components/editor/timeline/TimelinePlayhead.vue").default>
  'LazyEditorTimelineRuler': LazyComponent<typeof import("../../app/components/editor/timeline/TimelineRuler.vue").default>
  'LazyEditorTimelineStudioSync': LazyComponent<typeof import("../../app/components/editor/timeline/TimelineStudioSync.vue").default>
  'LazyEditorTimelineToolbar': LazyComponent<typeof import("../../app/components/editor/timeline/TimelineToolbar.vue").default>
  'LazyEditorTimelineConstants': LazyComponent<typeof import("../../app/components/editor/timeline/timeline-constants").default>
  'LazyEditorTimelineTimelineCanvas': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/canvas").default>
  'LazyEditorTimelineTimelineClipsAudio': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/audio").default>
  'LazyEditorTimelineTimelineClipsBase': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/base").default>
  'LazyEditorTimelineTimelineClipsCaption': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/caption").default>
  'LazyEditorTimelineTimelineClipsEffect': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/effect").default>
  'LazyEditorTimelineTimelineClipsImage': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/image").default>
  'LazyEditorTimelineTimelineClips': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/index").default>
  'LazyEditorTimelineTimelineClipsText': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/text").default>
  'LazyEditorTimelineTimelineClipsTransition': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/transition").default>
  'LazyEditorTimelineTimelineClipsVideo': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/clips/video").default>
  'LazyEditorTimelineTimelineControlsConstants': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/controls/constants").default>
  'LazyEditorTimelineTimelineControls': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/controls/index").default>
  'LazyEditorTimelineTimelineControlsRender': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/controls/render").default>
  'LazyEditorTimelineTimelineControlsResizeAction': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/controls/resize-action").default>
  'LazyEditorTimelineTimelineControlsTrimAction': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/controls/trim-action").default>
  'LazyEditorTimelineTimelineControlsUtils': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/controls/utils").default>
  'LazyEditorTimelineTimelineData': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/data").default>
  'LazyEditorTimelineTimelineEventEmitter': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/event-emitter").default>
  'LazyEditorTimelineTimelineGuidelinesUtils': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/guidelines/utils").default>
  'LazyEditorTimelineTimelineHandlersDragHandler': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/handlers/drag-handler").default>
  'LazyEditorTimelineTimelineHandlersModifyHandler': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/handlers/modify-handler").default>
  'LazyEditorTimelineTimelineHandlersSelection': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/handlers/selection").default>
  'LazyEditorTimelineTimeline': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/index").default>
  'LazyEditorTimelineTimelineObjectsTransitionButton': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/objects/transition-button").default>
  'LazyEditorTimelineTimelineScrollbar': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/scrollbar/index").default>
  'LazyEditorTimelineTimelineScrollbarTypes': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/scrollbar/types").default>
  'LazyEditorTimelineTimelineScrollbarUtil': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/scrollbar/util").default>
  'LazyEditorTimelineTimelineTrack': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/track").default>
  'LazyEditorTimelineTimelineUtilsFilmstrip': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/utils/filmstrip").default>
  'LazyEditorTimelineTimelineUtilsThumbnailCache': LazyComponent<typeof import("../../app/components/editor/timeline/timeline/utils/thumbnail-cache").default>
  'LazySharedIcons': LazyComponent<typeof import("../../app/components/shared/icons").default>
  'LazySharedLogos': LazyComponent<typeof import("../../app/components/shared/logos").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyButton': LazyComponent<typeof import("../../app/components/ui/button/index").Button>
  'LazyDropdownMenu': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenu>
  'LazyDropdownMenuCheckboxItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuCheckboxItem>
  'LazyDropdownMenuContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuContent>
  'LazyDropdownMenuGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuGroup>
  'LazyDropdownMenuItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuItem>
  'LazyDropdownMenuLabel': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuLabel>
  'LazyDropdownMenuRadioGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuRadioGroup>
  'LazyDropdownMenuRadioItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuRadioItem>
  'LazyDropdownMenuSeparator': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSeparator>
  'LazyDropdownMenuShortcut': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuShortcut>
  'LazyDropdownMenuSub': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSub>
  'LazyDropdownMenuSubContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSubContent>
  'LazyDropdownMenuSubTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuSubTrigger>
  'LazyDropdownMenuTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuTrigger>
  'LazyDropdownMenuPortal': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index").DropdownMenuPortal>
  'LazyInput': LazyComponent<typeof import("../../app/components/ui/input/index").Input>
  'LazyPopover': LazyComponent<typeof import("../../app/components/ui/popover/index").Popover>
  'LazyPopoverAnchor': LazyComponent<typeof import("../../app/components/ui/popover/index").PopoverAnchor>
  'LazyPopoverContent': LazyComponent<typeof import("../../app/components/ui/popover/index").PopoverContent>
  'LazyPopoverTrigger': LazyComponent<typeof import("../../app/components/ui/popover/index").PopoverTrigger>
  'LazyInputGroup': LazyComponent<typeof import("../../app/components/ui/input-group/index").InputGroup>
  'LazyInputGroupAddon': LazyComponent<typeof import("../../app/components/ui/input-group/index").InputGroupAddon>
  'LazyInputGroupButton': LazyComponent<typeof import("../../app/components/ui/input-group/index").InputGroupButton>
  'LazyInputGroupInput': LazyComponent<typeof import("../../app/components/ui/input-group/index").InputGroupInput>
  'LazyInputGroupText': LazyComponent<typeof import("../../app/components/ui/input-group/index").InputGroupText>
  'LazyInputGroupTextarea': LazyComponent<typeof import("../../app/components/ui/input-group/index").InputGroupTextarea>
  'LazyResizableHandle': LazyComponent<typeof import("../../app/components/ui/resizable/index").ResizableHandle>
  'LazyResizablePanel': LazyComponent<typeof import("../../app/components/ui/resizable/index").ResizablePanel>
  'LazyResizablePanelGroup': LazyComponent<typeof import("../../app/components/ui/resizable/index").ResizablePanelGroup>
  'LazyScrollArea': LazyComponent<typeof import("../../app/components/ui/scroll-area/index").ScrollArea>
  'LazyScrollBar': LazyComponent<typeof import("../../app/components/ui/scroll-area/index").ScrollBar>
  'LazySeparator': LazyComponent<typeof import("../../app/components/ui/separator/index").Separator>
  'LazySlider': LazyComponent<typeof import("../../app/components/ui/slider/index").Slider>
  'LazyTabs': LazyComponent<typeof import("../../app/components/ui/tabs/index").Tabs>
  'LazyTabsContent': LazyComponent<typeof import("../../app/components/ui/tabs/index").TabsContent>
  'LazyTabsList': LazyComponent<typeof import("../../app/components/ui/tabs/index").TabsList>
  'LazyTabsTrigger': LazyComponent<typeof import("../../app/components/ui/tabs/index").TabsTrigger>
  'LazyTooltip': LazyComponent<typeof import("../../app/components/ui/tooltip/index").Tooltip>
  'LazyTooltipContent': LazyComponent<typeof import("../../app/components/ui/tooltip/index").TooltipContent>
  'LazyTooltipProvider': LazyComponent<typeof import("../../app/components/ui/tooltip/index").TooltipProvider>
  'LazyTooltipTrigger': LazyComponent<typeof import("../../app/components/ui/tooltip/index").TooltipTrigger>
  'LazyTextarea': LazyComponent<typeof import("../../app/components/ui/textarea/index").Textarea>
  'LazyNuxtPage': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/pages/runtime/page-placeholder").default>
  'LazyNoScript': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@biomejs+biome@2.3.8_@parcel+watcher@2.5.6_@types+node@25.0.8_@vue+compiler-sfc@3._dv56lvvhyfshsdtdojidzrymfi/node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
