// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/audio/music': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/music.post').default>>>>
    }
    '/api/audio/sfx': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/sfx.post').default>>>>
    }
    '/api/elevenlabs/music': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elevenlabs/music.post').default>>>>
    }
    '/api/elevenlabs/sfx': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elevenlabs/sfx.post').default>>>>
    }
    '/api/elevenlabs/voiceover': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elevenlabs/voiceover.post').default>>>>
    }
    '/api/pexels': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pexels.get').default>>>>
    }
    '/api/transcribe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transcribe.post').default>>>>
    }
    '/api/uploads/presign': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploads/presign.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+nitro-server@4.2.2_db0@0.3.4_ioredis@5.9.2_magicast@0.5.2_nuxt@4.2.2_@biomejs+biome@2.3_dbnjtlatgyd7xf66uanqesuhbm/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}